# Numpy Array

In [1]:
import numpy as np

In [3]:
my_lst = [1,2,3,4,5]
arr = np.array(my_lst)

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr

array([1, 2, 3, 4, 5])

In [9]:
arr.shape

(5,)

In [32]:
lst1 = [4,56,6,7,8,6,8,]
lst2 = [21,4,6,7,2,88,8]
lst3 = [3,6,899,9,34,6,67]
arr = np.array([lst1,lst2,lst3])

In [33]:
arr

array([[  4,  56,   6,   7,   8,   6,   8],
       [ 21,   4,   6,   7,   2,  88,   8],
       [  3,   6, 899,   9,  34,   6,  67]])

In [34]:
arr.shape

(3, 7)

In [35]:
arr.reshape(7,3)

array([[  4,  56,   6],
       [  7,   8,   6],
       [  8,  21,   4],
       [  6,   7,   2],
       [ 88,   8,   3],
       [  6, 899,   9],
       [ 34,   6,  67]])

In [36]:
arr

array([[  4,  56,   6,   7,   8,   6,   8],
       [ 21,   4,   6,   7,   2,  88,   8],
       [  3,   6, 899,   9,  34,   6,  67]])

In [37]:
arr[0:2,0:2]

array([[ 4, 56],
       [21,  4]])

In [38]:
arr[1:,4:6]

array([[ 2, 88],
       [34,  6]])

In [42]:
arr[1:2,1:4]

array([[4, 6, 7]])

In [63]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
np.linspace(0,50,11)

array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [65]:
arr1 = arr.copy()

In [66]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
arr1[3:] = 500

In [68]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
arr<2

array([ True,  True, False, False, False, False, False, False, False,
       False])

In [70]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [72]:
arr[arr<3]

array([0, 1, 2])

In [74]:
np.ones(4, dtype = int)

array([1, 1, 1, 1])

In [75]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [76]:
np.random.rand(3,3)

array([[0.36952608, 0.39118711, 0.01549998],
       [0.02837987, 0.77692237, 0.97660636],
       [0.8305429 , 0.13750252, 0.05153498]])

In [79]:
arr = np.random.randn(4,4)

In [82]:
arr

array([[ 0.03695349,  0.64489551,  0.0418434 , -1.31138337],
       [ 0.23958934,  0.04211204,  2.37169259,  0.19427947],
       [-0.84601089,  0.37398758, -0.1023978 ,  1.25454411],
       [-0.58402487,  0.26429225,  1.52386539, -0.48530306]])

In [87]:
np.random.randint(0,10,8).reshape(2,4)

array([[8, 0, 3, 8],
       [1, 1, 5, 4]])

In [91]:
np.random.random_sample((1,5))

array([[0.29303456, 0.61371078, 0.59272914, 0.67969943, 0.20875115]])